src/Entity/Feed.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FeedRepository")
 */
class Feed
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var Patient
     *
     * @ORM\ManyToOne(targetEntity="Patient", inversedBy="feeds")
     * @ORM\JoinColumn(nullable=false)
     */
    private $patient;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="Answer", mappedBy="feed", cascade={"all"})
     * @ORM\OrderBy({"id" = "ASC"})
     *
     * @Assert\Valid()
     */
    private $answers;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $synopsis;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $createdAt;


    public function __construct()
    {
        $this->answers = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Patient
     */
    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    /**
     * @param Patient $patient
     *
     * @return $this
     */
    public function setPatient(Patient $patient): self
    {
        $this->patient = $patient;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    /**
     * @param Answer $answer
     *
     * @return $this
     */
    public function addAnswer(Answer $answer): self
    {
        $this->answers[] = $answer->setFeed($this);

        return $this;
    }

    /**
     * @param Answer $answer
     */
    public function removeAnswer(Answer $answer)
    {
        $this->answers->removeElement($answer);
    }

    /**
     * @return string
     */
    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    /**
     * @param string $synopsis
     *
     * @return $this
     */
    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Entity/Phone.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PhoneRepository")
 */
class Phone
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var Patient
     *
     * @ORM\ManyToOne(targetEntity="Patient", inversedBy="phones")
     * @ORM\JoinColumn(nullable=false)
     */
    private $patient;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=20)
     *
     * @Assert\NotBlank()
     * @Assert\Length(max=20)
     */
    private $number;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $comment;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $removedAt;


    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Patient
     */
    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    /**
     * @param Patient $patient
     *
     * @return $this
     */
    public function setPatient(Patient $patient): self
    {
        $this->patient = $patient;

        return $this;
    }

    /**
     * @return string
     */
    public function getNumber(): ?string
    {
        return $this->number;
    }

    /**
     * @param string $number
     *
     * @return $this
     */
    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * @return string
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }

    /**
     * @param string $comment
     *
     * @return $this
     */
    public function setComment(string $comment = null): self
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getRemovedAt(): ?\DateTime
    {
        return $this->removedAt;
    }

    /**
     * @param \DateTime $removedAt
     *
     * @return $this
     */
    public function setRemovedAt(\DateTime $removedAt): self
    {
        $this->removedAt = $removedAt;

        return $this;
    }

    public function isPrimary(): bool
    {
        return $this->getPatient() && $this->getPatient()->getPrimary() === $this;
    }
}

src/Form/FeedType.php
<?php

namespace App\Form;

use App\Entity\Feed;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FeedType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('synopsis')
            ->add('answers', CollectionType::class, [
                'entry_type' => AnswerType::class,
                'allow_delete' => true,
                'by_reference' => false,
            ])
            ->add('save', SubmitType::class)
            ->add('defer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Feed::class,
        ]);
    }
}

src/Controller/FeedController.php
<?php

namespace App\Controller;

use App\Entity\Choice;
use App\Entity\ChoiceAnswer;
use App\Entity\CompletionAnswer;
use App\Entity\Feed;
use App\Entity\Patient;
use App\Entity\Question;
use App\Form\FeedType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class FeedController
{
    /**
     * @Route("/patients/{patient}/feeds/new", methods="GET")
     *
     * @Template()
     */
    public function new(Patient $patient, FormFactoryInterface $ff, UrlGeneratorInterface $g, EntityManagerInterface $em)
    {
        $form = $ff->create(FeedType::class, $this->forge($em), [
            'action' => $g->generate('app_feed_create', [ 'patient' => $patient->getId() ]),
            'method' => 'POST',
        ]);

        return [
            'form' => $form->createView(),
            'patient' => $patient,
            'questions' => $em->getRepository(Question::class)->findBy([], [ 'id' => 'ASC' ]),
        ];
    }

    /**
     * @Route("/patients/{patient}/feeds", methods="POST")
     *
     * @Template("feed/new.html.twig")
     */
    public function create(Patient $patient, Request $request, FormFactoryInterface $ff, UrlGeneratorInterface $g, EntityManagerInterface $em)
    {
        $form = $ff->create(FeedType::class, $this->forge($em), [
            'action' => $g->generate('app_feed_create', [ 'patient' => $patient->getId() ]),
            'method' => 'POST',
        ]);

        $form->handleRequest($request);
        if (!$form->isValid()) {
            return [
                'form' => $form->createView(),
                'patient' => $patient,
                'questions' => $em->getRepository(Question::class)->findBy([], [ 'id' => 'ASC' ]),
            ];
        }

        $feed = $form->getData();
        $feed
            ->setPatient($patient)
            ->setCreatedAt(new \DateTime())
        ;
        foreach ($feed->getAnswers() as $answer) {
            if ($form->get('defer')->isClicked()
                || empty($answer->getValue())) {
                $feed->removeAnswer($answer);
            }
        }
        $patient->setExpireAt(new \DateTime($feed->getAnswers()->count() > 0 ? '+1 year' : '+1 week'));
        $em->persist($feed);
        $em->flush();

        return new RedirectResponse($g->generate('app_patient_show', [ 'patient' => $patient->getId() ]));
    }

    private function forge(EntityManagerInterface $em)
    {
        $feed = new Feed();
        foreach ($em->getRepository(Question::class)->findBy([], [ 'id' => 'ASC' ]) as $q) {
            $feed->addAnswer(
                $q instanceof Choice
                ? (new ChoiceAnswer())->setChoice($q)
                : (new CompletionAnswer())->setCompletion($q)
            );
        }

        return $feed;
    }
}

templates/feed/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="column">
        {{ form_start(form, { attr: { class: 'ui form' } }) }}
            <h1 class="ui header">
                {{ patient.name }} ({{ patient.cId }})
                <small><i class="{{ patient.male ? 'man' : 'woman' }} icon"></i></small>
                <div class="sub header">{{ patient.physician }}</div>
            </h1>

            <div>
		<div>
                    {% for phone in patient.phones if not phone.removedAt %}
			<div class="{% if phone.primary %}primary {% endif %} phone" data-url="{{ path('app_phone_delete', { patient: patient.id, phone: phone.id }) }}">
			    <span class="number">{{ phone.number }}</span>
			    <small style="margin-left: 1em;">
				<a href="javascript:;" class="default">默认</a>
				<a href="javascript:;" class="remove" style="margin-left: .5em;">删除</a>
			    </small>
			</div>
                    {% endfor %}
		    <a href="javascript:;" class="fu-add-phone" data-url="{{ path('app_phone_create', { patient: patient.id }) }}">
			增加
		    </a>
		    <script type="text/x-handlebars-template">
			<div class="phone" data-url="{{ '{{ url }}' }}">
			    <span class="number">{{ '{{ number }}' }}</span>
			    <small style="margin-left: 1em;">
				<a href="javascript:;" class="default">默认</a>
				<a href="javascript:;" class="remove" style="margin-left: .5em;">删除</a>
			    </small>
			</div>
		    </script>
		</div>
                <br>

                {{ patient.institution }}
                <br>
                {{ patient.district }}
                {{ patient.street }}
            </div>

	    <br>
            <div class="field">
                <label>备注</label>
                {{ form_widget(form.synopsis) }}
            </div>

            {{ form_widget(form.defer, { attr: { class: 'ui button' }, label: '延期' }) }}

            <h1 class="ui header">随访</h1>

            {% for answer in form.answers %}
                <div class="field">
                    {{ form_label(answer.value) }}
                    {% for opt in answer.value.children %}
                        <div class="field">
                            <div class="ui radio checkbox">
                                {{ form_widget(opt, { required: false }) }}
                                {{ form_label(opt) }}
                            </div>
                        </div>
                    {% endfor %}
                    {% if answer.vars.value.completion is defined %}
                        {{ form_widget(answer.value, { required: false, type: answer.vars.value.completion.date ? 'date' : 'text' }) }}
                    {% endif %}

                    {% do answer.comment.setRendered %}
                </div>
            {% endfor %}

            {{ form_widget(form.save, { attr: { class: 'ui primary button' }, label: '保存' }) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script>
     $('.phone .default').click(function (e) {
         e.preventDefault();

         var phone = $(this).closest('.phone');
         $
	     .ajax(phone.data('url'), { method: 'PUT' })
	     .then(function () {
	         phone.siblings('.phone').removeClass('primary');
	         phone.addClass('primary');
	     })
         ;
     });

     $('.phone .remove').click(function (e) {
         e.preventDefault();

         var phone = $(this).closest('.phone');
         $
	     .ajax(phone.data('url'), { method: 'DELETE' })
	     .then(function () {
	         phone.remove();
	     })
         ;
     });

     $('.fu-add-phone').click(function (e) {
         e.preventDefault();

         var number = window.prompt('请输入新的联系方式:');
         if (number) {
	     var anchor = $(this);
	     $
	         .post(anchor.data('url'), {
		     'phone[number]': number,
	         })
	         .then(function (data) {
		     var tmpl = Handlebars.compile(anchor.next('script').html());
		     anchor.before(tmpl(data));
	         })
	     ;
         }
     });
    </script>
{% endblock %}